---
name: Deployment

on:
  push:
    branches: [ develop ]

jobs:  
  build-and-deploy-app:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        
      - name: Install node
        run: npm install --legacy-peer-deps

      - name: Production Build
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'dist/apps/the-au-pair'

  package-api:
    needs: build-and-deploy-app
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file Server/pom.xml

      - name: Save JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: Server/target/The-Au-Pair-0.0.1-SNAPSHOT.jar
  
  ec2-deploy:
    name: Deploy to EC2
     runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    
